// flow-typed signature: c04e732e3391b5c9564082a361832b93
// flow-typed version: <<STUB>>/p-event_v^2.1.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-event/index' {
  declare module.exports: $Exports<'p-event'>;
}
declare module 'p-event/index.js' {
  declare module.exports: $Exports<'p-event'>;
}
