version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.20
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - checkout

      - run:
          name: Setup NPM Token
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            echo "registry=https://registry.npmjs.org/" >> .npmrc

      # https://github.com/atlassian/react-beautiful-dnd/issues/1007#issuecomment-446415426
      - run:
          name: Workaround for Flow crashing
          command: echo "server.max_workers=1" >> .flowconfig

      - run:
          name: Install pnpm
          command: sudo npm install --global pnpm
      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile
      - run:
          name: build
          command: pnpm prepublishOnly
      - run:
          name: upload test coverage
          command: pnpm codecov
      - run:
          name: release
          command: pnpm semantic-release
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - github-release
            - npm-release
